### ISSUE TITLE
Obtaining latest ystockquote

### ISSUE THREAD

**Issue by ifuchs** [cgoldberg/ystockquote#56]
Sorry if this is more of a Git question than ystockquote, but how exactly can I get the latest version of ystockquote? Thanks in advance.

**Comment by cgoldberg** [comment]
from the README:
```
ytockquote can be installed from PyPI with pip:
$ pip install ystockquote

You can also clone the development repo to install (requires git):
$ git clone git://github.com/cgoldberg/ystockquote.git
$ cd ystockquote
$ python setup.py install
```

you can also install master branch from the git repo with:
`$ pip install -e git+https://github.com/cgoldberg/ystockquote.git/#egg=ystockquote`

**Comment by ifuchs** [comment]
I tried that but it would appear that get_historical_prices is still broken? (v2.6dev)

>>> import ystockquote as yt
>>> yt.get_historical_price('ADBE','2018-03-09','2018-03-18')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'get_historical_price'
>>> yt.get_historical_prices('ADBE','2018-03-09','2018-03-18')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ystockquote.py", line 486, in get_historical_prices
    resp = urlopen(req)
  File "//anaconda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "//anaconda/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "//anaconda/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "//anaconda/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "//anaconda/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "//anaconda/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

**Comment by cgoldberg** [comment]
>  it would appear that get_historical_prices is still broken?

correct.
